# Generated by Django 4.1.5 on 2023-01-11 17:41

from django.db import migrations, models
import teachers.validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('birth_day', models.DateField(validators=[teachers.validators.validators.validate_age], verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['first_name', 'second_name'],
            },
        ),
    ]
