# Generated by Django 4.1.5 on 2023-01-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
