# Generated by Django 4.1.5 on 2023-01-11 17:54

from django.db import migrations, models
import teachers.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_day',
            field=models.DateField(validators=[teachers.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
