# Generated by Django 4.1.5 on 2023-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_teacher'),
        ('teachers', '0005_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='classes.class', verbose_name='Предметы'),
        ),
    ]
