# Generated by Django 4.1.5 on 2023-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0001_initial'),
        ('classes', '0002_remove_class_teacher'),
        ('teachers', '0007_remove_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='to_class',
            field=models.ManyToManyField(related_name='teachers', through='classboard.Classboard', to='classes.class', verbose_name='Предметы'),
        ),
    ]
