# Generated by Django 4.1.5 on 2023-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teacher_to_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_day',
            field=models.DateField(auto_now_add=True, verbose_name='Дата рождения'),
        ),
    ]
