# Generated by Django 4.1.5 on 2023-01-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacher_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='to_class',
        ),
    ]
