# Generated by Django 4.1.5 on 2023-01-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classwithteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classwithteacher',
            options={'verbose_name': 'Занятие + Учителя', 'verbose_name_plural': 'Занятия + Учителя'},
        ),
    ]
