# Generated by Django 4.1.5 on 2023-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_studentsclass_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('week_day', models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default='1', max_length=2, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Занятие + Студент',
                'verbose_name_plural': 'Занятия + Студенты',
            },
        ),
        migrations.DeleteModel(
            name='StudentsClass',
        ),
    ]
