# Generated by Django 4.1.5 on 2023-01-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_classroom_delete_classwithteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Занятие'),
        ),
    ]
