# Generated by Django 4.1.5 on 2023-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_classroom_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_pair', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['class_pair'],
            },
        ),
    ]
