# Generated by Django 4.1.5 on 2023-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_classpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['class_name']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_pair',
            field=models.CharField(choices=[('1', 'Первая пара'), ('2', 'Вторая пара'), ('3', 'Третья пара'), ('4', 'Четвертая пара'), ('5', 'Пятая пара'), ('6', 'Шестая пара'), ('7', 'Седьмая пара'), ('8', 'Восьмая пара')], default='1', max_length=6, verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='classpair',
            name='class_pair',
            field=models.CharField(choices=[('1', 'Первая пара'), ('2', 'Вторая пара'), ('3', 'Третья пара'), ('4', 'Четвертая пара'), ('5', 'Пятая пара'), ('6', 'Шестая пара'), ('7', 'Седьмая пара'), ('8', 'Восьмая пара')], default='1', max_length=6, verbose_name='Пара'),
        ),
    ]
