# Generated by Django 4.1.5 on 2023-01-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_class_day'),
        ('classes', '0013_alter_classroom_options_classroom_class_pair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
