# Generated by Django 4.1.5 on 2023-01-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_classroom_student_classroom_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
