# Generated by Django 4.1.5 on 2023-01-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_delete_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassPair',
        ),
    ]
