# Generated by Django 4.1.5 on 2023-01-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_delete_classpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.DeleteModel(
            name='ClassByDay',
        ),
    ]
