# Generated by Django 4.1.5 on 2023-01-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classboard',
            options={'ordering': ['class_name', 'teacher'], 'verbose_name': 'Расписание'},
        ),
    ]
