# Generated by Django 4.1.5 on 2023-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0003_alter_classboard_options_classboard_class_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classboard',
            name='class_day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default='1', max_length=6, verbose_name='День недели'),
        ),
    ]
