# Generated by Django 4.1.5 on 2023-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_teacher_phone'),
        ('classboard', '0004_alter_classboard_class_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classboard',
            name='teacher',
            field=models.ManyToManyField(related_name='classboard_teacher', to='teachers.teacher', verbose_name='Преподаватель'),
        ),
    ]
