# Generated by Django 4.1.5 on 2023-01-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_studentsclass_options'),
        ('students', '0002_alter_group_options_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='on_class',
            field=models.ManyToManyField(related_name='student_class', to='classes.class', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groupe', to='students.group', verbose_name='Группа'),
        ),
    ]
