# Generated by Django 4.1.5 on 2023-01-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='groupe',
            new_name='group',
        ),
    ]
