# Generated by Django 4.1.5 on 2023-01-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='year',
        ),
    ]
