# Generated by Django 4.1.5 on 2023-01-24 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0006_wage_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='year',
        ),
        migrations.AddField(
            model_name='wage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
