# Generated by Django 4.1.5 on 2023-01-24 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0007_remove_wage_month_remove_wage_year_wage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 24), verbose_name='Дата'),
        ),
    ]
