# Generated by Django 4.1.5 on 2023-01-24 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0008_alter_wage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
