# Generated by Django 4.1.5 on 2023-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0013_alter_wage_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оклад'),
        ),
    ]
