# Generated by Django 4.1.5 on 2023-01-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0014_alter_wage_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WageByYear',
        ),
    ]
